title: Alexey Naumov
description: >
  iOS development best practices, software architecture design, functional reactive programming, Swift, SwiftUI, Combine, UIKit
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nalexn.github.io"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Alexey Naumov
author-img: profile-image.jpg # add your photo
about-author: me
social-twitter: nallexn
social-stackoverflow: 2923345
social-github: nalexn
social-linkedin: nalexn
social-email: none

# Disqus
discus-identifier: nalexn

# Tracker
analytics: UA-96224610-1

# Build Settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 8
paginate_path: "/page/:num"

exclude: ["gulpfile.js", "package.json", "README.md", "Gemfile", "Gemfile.lock", "LICENSE"]
